url: "https://usages.kuartz.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kuartz" # the name of your site, e.g. ACME Corp.
email: contact@kuartz.fr
description: >-
  Nous concevons et développons des applications web et solutions de gestion
  performantes répondant à des problématiques business et techniques complexes.
twitter_username: guicabanel
github_username:  kuartz-org

plugins:
  - jekyll-postcss

sass:
  sourcemap: never

postcss:
  cache: false

exclude:
  - .gitignore
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - README.md

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map
