url: "https://cas-d-usages.kuartz.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kuartz" # the name of your site, e.g. ACME Corp.
email: contact@kuartz.fr
description: >-
  Nous concevons et développons des applications web et solutions de gestion
  performantes répondant à des problématiques business et techniques complexes.
twitter_username: guicabanel
github_username:  kuartz-org

plugins:
  - jekyll-postcss

css_dir: "assets/css"

exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - README.md
